# Generated by Django 5.0.6 on 2024-05-29 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='password',
        ),
    ]
